"""empty message

Revision ID: 1857377d6875
Revises: ea6cb15f3eae
Create Date: 2019-08-03 20:42:25.733556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1857377d6875'
down_revision = 'ea6cb15f3eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'address', 'user', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'person_id')
    # ### end Alembic commands ###
