"""empty message

Revision ID: 1aa2da630a3c
Revises: b9b2d89d4ca4
Create Date: 2019-08-02 20:48:39.470589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aa2da630a3c'
down_revision = 'b9b2d89d4ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'productPicture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('productPicture', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
