"""empty message

Revision ID: 679671e7e76d
Revises: f756ca6fc857
Create Date: 2019-08-09 15:30:59.609347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '679671e7e76d'
down_revision = 'f756ca6fc857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('productId', sa.Integer(), nullable=False))
    op.drop_constraint('pictures_ibfk_1', 'pictures', type_='foreignkey')
    op.create_foreign_key(None, 'pictures', 'products', ['productId'], ['id'])
    op.drop_column('pictures', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.create_foreign_key('pictures_ibfk_1', 'pictures', 'products', ['product_id'], ['id'])
    op.drop_column('pictures', 'productId')
    # ### end Alembic commands ###
