"""empty message

Revision ID: 985d03cbe3d5
Revises: fee12ea9be14
Create Date: 2019-08-03 16:42:20.376820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985d03cbe3d5'
down_revision = 'fee12ea9be14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pictureUrl', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture')
    # ### end Alembic commands ###
