"""empty message

Revision ID: a345217742a7
Revises: 68edce840981
Create Date: 2019-08-03 21:34:47.210549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a345217742a7'
down_revision = '68edce840981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=False))
    op.drop_index('email_1', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'email_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_1', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('email_1', 'user', ['email_1'], unique=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
