"""empty message

Revision ID: b19993f0c813
Revises: 011405215382
Create Date: 2019-08-04 18:57:50.773302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b19993f0c813'
down_revision = '011405215382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billingStreet', sa.String(length=45), nullable=True),
    sa.Column('billingNumber', sa.String(length=45), nullable=True),
    sa.Column('billingCity', sa.String(length=45), nullable=True),
    sa.Column('billingState', sa.String(length=45), nullable=True),
    sa.Column('billingZipCode', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=45), nullable=False),
    sa.Column('productDescription', sa.String(length=255), nullable=True),
    sa.Column('productPrice', sa.String(length=45), nullable=False),
    sa.Column('productCategory', sa.String(length=45), nullable=True),
    sa.Column('productAgeRange', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('productDescription'),
    sa.UniqueConstraint('productName')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userFirstName', sa.String(length=45), nullable=False),
    sa.Column('userLastName', sa.String(length=45), nullable=False),
    sa.Column('userName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userStreet', sa.String(length=45), nullable=False),
    sa.Column('userNumber', sa.String(length=45), nullable=False),
    sa.Column('userCity', sa.String(length=45), nullable=False),
    sa.Column('userState', sa.String(length=45), nullable=False),
    sa.Column('userZipCode', sa.String(length=12), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('email', table_name='user')
    op.drop_index('userName', table_name='user')
    op.drop_table('user')
    op.drop_index('productDescription', table_name='product')
    op.drop_index('productName', table_name='product')
    op.drop_table('product')
    op.drop_table('address')
    op.drop_table('billing_address')
    op.drop_table('picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('picture_url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('billing_address',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('billingStreet', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('billingNumber', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('billingCity', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('billingState', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('billingZipCode', mysql.VARCHAR(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('address',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userStreet', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('userNumber', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('userCity', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('userState', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('userZipCode', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('person_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['user.id'], name='address_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('product',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('productName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('productDescription', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('productPrice', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('productCategory', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('productAgeRange', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('productName', 'product', ['productName'], unique=True)
    op.create_index('productDescription', 'product', ['productDescription'], unique=True)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userFirstName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('userName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('userLastName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('userName', 'user', ['userName'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('pictures')
    op.drop_table('billing_addresses')
    # ### end Alembic commands ###
