"""empty message

Revision ID: b9b2d89d4ca4
Revises: be9c8416644e
Create Date: 2019-08-02 19:22:27.492377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9b2d89d4ca4'
down_revision = 'be9c8416644e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userStreet', sa.String(length=45), nullable=True),
    sa.Column('userNumber', sa.String(length=45), nullable=True),
    sa.Column('userCity', sa.String(length=45), nullable=True),
    sa.Column('userState', sa.String(length=45), nullable=True),
    sa.Column('userZipCode', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billingStreet', sa.String(length=45), nullable=True),
    sa.Column('billingNumber', sa.String(length=45), nullable=True),
    sa.Column('billingCity', sa.String(length=45), nullable=True),
    sa.Column('billingState', sa.String(length=45), nullable=True),
    sa.Column('billingZipCode', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=45), nullable=False),
    sa.Column('productDescription', sa.String(length=255), nullable=True),
    sa.Column('productPrice', sa.String(length=45), nullable=False),
    sa.Column('productPicture', sa.String(length=255), nullable=True),
    sa.Column('productCategory', sa.String(length=45), nullable=True),
    sa.Column('productAgeRange', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('productDescription'),
    sa.UniqueConstraint('productName')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userFirstName', sa.String(length=45), nullable=False),
    sa.Column('userLastName', sa.String(length=45), nullable=False),
    sa.Column('userName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userName')
    )
    op.drop_index('email', table_name='person')
    op.drop_index('username', table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'person', ['username'], unique=True)
    op.create_index('email', 'person', ['email'], unique=True)
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('billing_address')
    op.drop_table('address')
    # ### end Alembic commands ###
