"""empty message

Revision ID: dc256e640729
Revises: 679671e7e76d
Create Date: 2019-08-09 15:38:24.057564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc256e640729'
down_revision = '679671e7e76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('photos_id', sa.Integer(), nullable=False))
    op.drop_constraint('pictures_ibfk_1', 'pictures', type_='foreignkey')
    op.create_foreign_key(None, 'pictures', 'products', ['photos_id'], ['id'])
    op.drop_column('pictures', 'productId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('productId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.create_foreign_key('pictures_ibfk_1', 'pictures', 'products', ['productId'], ['id'])
    op.drop_column('pictures', 'photos_id')
    # ### end Alembic commands ###
