"""empty message

Revision ID: e4873433fa3a
Revises: 1857377d6875
Create Date: 2019-08-03 21:06:15.065937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4873433fa3a'
down_revision = '1857377d6875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_lastName', sa.String(length=45), nullable=False))
    op.drop_column('user', 'userLastName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userLastName', mysql.VARCHAR(length=45), nullable=False))
    op.drop_column('user', 'user_lastName')
    # ### end Alembic commands ###
