"""empty message

Revision ID: ea6cb15f3eae
Revises: 4ed8b7743d9e
Create Date: 2019-08-03 18:17:33.707044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea6cb15f3eae'
down_revision = '4ed8b7743d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('picture_url', sa.Text(), nullable=False))
    op.drop_column('picture', 'pictureUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('pictureUrl', mysql.VARCHAR(length=45), nullable=False))
    op.drop_column('picture', 'picture_url')
    # ### end Alembic commands ###
