"""empty message

Revision ID: f756ca6fc857
Revises: fdd188edbe5a
Create Date: 2019-08-09 14:13:42.715393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f756ca6fc857'
down_revision = 'fdd188edbe5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pictures', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.drop_column('pictures', 'product_id')
    # ### end Alembic commands ###
