"""empty message

Revision ID: fdd188edbe5a
Revises: 3925afa4242b
Create Date: 2019-08-09 13:52:49.923035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd188edbe5a'
down_revision = '3925afa4242b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_addresses', sa.Column('person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'billing_addresses', 'users', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billing_addresses', type_='foreignkey')
    op.drop_column('billing_addresses', 'person_id')
    # ### end Alembic commands ###
